name: Publish to gh-pages
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/master')
    steps:
      - uses: actions/checkout@v2.2.0
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --frozen-lockfile
      - run: yarn run deploy
